pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        def props = new Properties()
        def githubProps = file("github.properties")
        if (githubProps.exists()) {
            githubProps.withInputStream { props.load(it) }
        }
        maven {
            url {"https://maven.pkg.github.com/UtiqTech/android-sdk"}
            credentials {
                username = props.getProperty('username', System.getenv('GITHUB_USER') ?: '')
                password = props.getProperty('token', System.getenv('GITHUB_TOKEN') ?: '')
            }
        }
    }
}
rootProject.name = "teavaroDemoApp"
include ':app'
