object Libraries {
    const val jUnit = "org.jetbrains.kotlin:kotlin-test-junit5:${Versions.kotlin}"
    const val testRunner = "androidx.test:runner:${Versions.testRunner}"
    const val onetrustSDK = "com.onetrust.cmp:native-sdk:${Versions.onetrustSDK}"
    const val stdlib = "org.jetbrains.kotlin:kotlin-stdlib:${Versions.kotlin}"
    const val ktxCore = "androidx.core:core-ktx:${Versions.androidXCore}"
    const val appCompat = "androidx.appcompat:appcompat:${Versions.appCompat}"
    const val material = "com.google.android.material:material:${Versions.material}"
    const val lifecycleCommon = "androidx.lifecycle:lifecycle-common-java8:${Versions.lifecycle}"
    const val lifecycleProcess = "androidx.lifecycle:lifecycle-process:${Versions.lifecycle}"
    const val constraintLayout = "androidx.constraintlayout:constraintlayout:${Versions.constraintLayout}"
    const val viewBinding = "androidx.databinding:viewbinding:${Versions.viewBinding}"
    const val activityX = "androidx.activity:activity-ktx:${Versions.activityX}"
    const val fragmentX = "androidx.fragment:fragment-ktx:${Versions.fragmentX}"
    const val androidXWorkRuntime = "androidx.work:work-runtime-ktx:${Versions.androidXWorkRuntime}"
    const val facebookFlipper = "com.facebook.flipper:flipper:${Versions.facebookFlipper}"
    const val facebookFlipperSoloader = "com.facebook.soloader:soloader:${Versions.facebookSoloader}"
    const val facebookFlipperNetworkPlugin = "com.facebook.flipper:flipper-network-plugin:${Versions.facebookFlipper}"
    const val facebookFlipperNoop = "com.github.theGlenn:flipper-android-no-op:${Versions.facebookFlipperNoop}"
    const val hyperionCore = "com.willowtreeapps.hyperion:hyperion-core:${Versions.hyperion}"
    const val hyperionSharedPreferences = "com.willowtreeapps.hyperion:hyperion-shared-preferences:${Versions.hyperion}"
    const val hyperionNoop = "com.willowtreeapps.hyperion:hyperion-core-no-op:${Versions.hyperion}"
    const val swrve = "com.swrve.sdk.android:swrve-firebase:${Versions.swrve}"
    const val swrveGeo = "com.swrve.sdk.android:swrve-geo:${Versions.swrveGeo}"
    const val teavaroSDK = "com.github.Teavaro:FunnelConnect-SDK:${Versions.teavaro}"
    const val googleServices = "com.google.gms:google-services:${Versions.googleServices}"
}